version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - 0.0.0.0:80:8080
  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo:/data/db
volumes:
  mongo:
